{{ if eq .chezmoi.os "linux" -}}

["bin/op"]
type = "archive"
url = "https://cache.agilebits.com/dist/1P/op2/pkg/v{{ .op_cli_version }}/op_linux_amd64_v{{ .op_cli_version }}.zip"
exact = true
refreshPeriod = "168h"

{{- else if .chezmoi.os "darwin" -}}

[".installers/install_homebrew.sh"]
type = "file"
url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
exact = true

[".config/bash/.iterm2_shell_integration.bash"]
type = "file"
url = "https://iterm2.com/shell_integration/bash"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/iterm2-shell-integration.zsh"]
type = "file"
url = "https://iterm2.com/shell_integration/zsh"
exact = true
refreshPeriod = "168h"

{{ end -}}
