[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
exact = true
refreshPeriod = "168h"

[".nvm"]
type = "git-repo"
url = "https://github.com/nvm-sh/nvm.git"
clone.args = ["-b", "v{{ .nvm_version }}"]
exact = true

[".rvm"]
type = "git-repo"
url = "https://github.com/rvm/rvm.git"
clone.args = ["-b", "{{ .rvm_version }}"]
refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" -}}

[".linuxbrew"]
type = "git-repo"
url = "https://github.com/Homebrew/brew"
exact = true
refreshPeriod = "168h"

["bin/op"]
type = "archive"
url = "https://cache.agilebits.com/dist/1P/op2/pkg/v{{ .op_cli_version }}/op_linux_amd64_v{{ .op_cli_version }}.zip"
exact = true
refreshPeriod = "168h"

{{- else if .chezmoi.os "darwin" -}}

[".installers/install_homebrew.sh"]
type = "file"
url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
exact = true

[".config/bash/.iterm2_shell_integration.bash"]
type = "file"
url = "https://iterm2.com/shell_integration/bash"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/iterm2-shell-integration.zsh"]
type = "file"
url = "https://iterm2.com/shell_integration/zsh"
exact = true
refreshPeriod = "168h"

{{ end -}}
