{{ if eq .chezmoi.os "linux" -}}

#["bin/op"]
#  type = "file"
#  url = "https://cache.agilebits.com/dist/1P/op2/pkg/v{{ .version.op_cli }}/op_linux_amd64_v{{ .version.op_cli }}.zip"
#  exact = true
#  refreshPeriod = "168h"
#  ["bin/op".filter]
#    command = "unzip"
#    args = ["-p", "/dev/stdin", "op"]

{{- else if eq .chezmoi.os "darwin" -}}

[".config/bash/.iterm2_shell_integration.bash"]
type = "file"
url = "https://iterm2.com/shell_integration/bash"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/iterm2-shell-integration.zsh"]
type = "file"
url = "https://iterm2.com/shell_integration/zsh"
exact = true
refreshPeriod = "168h"

{{ end -}}

